### ISSUE TITLE
Hub menu, video title & combined widget format issues with CJK font

### ISSUE THREAD

**Issue by satelly1** [jurialmunkey/skin.arctic.fuse.2#110]
### Skin section

Other

### Current Behavior

When CJK font is selected, the hub menu, video title and combined widget text appear to be slightly too low. For example the categories titles are lower than the hub label. They also appear to sitting lower within the blue selected bar. For the video title, the second line is touching the info panel. 

### Expected Behavior

Raise the height of the hub menu, second line of video title and combined widget title.

### Steps To Reproduce

1. Set up hub with in complex mode and combined widgets
2. Choose hub as home menu
3. Select CJK font

### Screenshots and Additional Info

<img width="1235" alt="Hub menu" src="https://github.com/user-attachments/assets/45cf49ce-552c-4801-be68-920238a0da4b">

<img width="1239" alt="Combined" src="https://github.com/user-attachments/assets/b1188d13-01f1-4156-ba10-c929e049ade9">

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yes, unfortunately the font is not very good.

Kodi doesn't have any support for fallback fonts for missing characters, so unfortunately you get weird height spacing issues. 

The CJK font is not recommended to use if you primarily use Kodi in English (or other latin alphabet languages).

**Comment by jurialmunkey** [comment]
I won't be able to fix these issues. The recommendation is to not use the font unless you absolutely have no other option (e.g. If you can only read Chinese and need the entire interface in Chinese).

**Comment by satelly1** [comment]
Thanks for your explanation. I have a library of Chinese & Korean series so do like having the original language in the title/plot etc. It is a minor issue and I can convert all to English. Your previous skins AH2 and AF, the CJK font seem to work very well without the current formating issues. Is this related to either the 2 line title that you now have or the auto height textbox? 


<img width="1247" alt="Arctic Horizon 2" src="https://github.com/user-attachments/assets/ed9056b4-20e1-47e5-8b84-14db9182681d">

<img width="1234" alt="Arctic Fuse" src="https://github.com/user-attachments/assets/4c38f2ba-7040-441b-82f0-8be81e43e8e4">

**Comment by jurialmunkey** [comment]
@satelly1 In a roundabout way, yes, but the problem itself is how Kodi does its calculation of linespacing based upon the tallest / longest character in the set. The CJK set has some characters with larger heights and so it causes the entire font to be shifted down in position when top alignment is used.

You can see this problem even in your screenshots of AH2 where the font is badly offset in the plotbox. You can see that it is pushed too far down so that the descenders on the g and y characters end up cut-off.

Your second screenshot of AF is not even using the CJK font, so that's why it looks fine there. I can tell it isn't being used because there is no Black weight in the CJK font but in your screenshot I can see that the Black weight is being used for the title and header.

Anyway, I have made an update to the CJK font resource which significantly improves the font. 
v0.0.2 will provide a RobotoCondensed version that is significantly better in terms of linespacing heights and when used with v2.0.14+ of the skin, will provide a significantly improved experience.

**Comment by satelly1** [comment]
Thanks again for the update. You have a great eye for detail as I have never noticed those issues before.
