### ISSUE TITLE
:bug: ActivateWindow(home) takes me to home page but also opens up the Options menu

### ISSUE THREAD

**Issue by booyakafoo** [jurialmunkey/skin.arctic.fuse.2#115]
### Skin section

Other

### Current Behavior

I have a keymap setup for F6 to ActivateWindow(home).  This is used to quickly get to the home screen from anywhere.  It still works but when using it, it will activate the home window and then open the Options pane that pops out from the right side of the screen.  

### Expected Behavior

Should activate the home window and not open the options pane. 

### Steps To Reproduce

Go to any window, Guide for example
Send command ActivateWindow(home)
You are brought to Home window but the Options pane also slides open from the right side

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Did you set a different hub to use as home?

If so you have to change your keymap to activate that hub window, not home.

That's the exact behaviour that happens when replacing home with a hub - it doesn't actually change the home screen, when the home screen loads it immediately replaces home with whatever window you've chosen and then triggers option menu (so that pressing back from the hub still has a way to open options).

**Comment by booyakafoo** [comment]
Yes, that is exactly what I did.  I set hub 1109 for use as home.  Updating the keymap to ActivateWindow(1109) is working perfectly.  Thanks

**Comment by jurialmunkey** [comment]
Just FYI next version will resolve this issue by making the "use as home" option properly replace the home window with the hub (i.e. it replaces its actual code with the relevant hub window code rather than just hacking it to take you back).

It should still work with your keymap change (I'm doing the reverse now - if you open the hub it replaces itself with home) but after next version you should be able to go back to having the keymap link to ActivateWindow(Home) instead.
