### ISSUE TITLE
:bug: Chinese characters garbled

### ISSUE THREAD

**Issue by yangyiminger** [jurialmunkey/skin.arctic.fuse.2#124]
### Skin section

Fonts and Languages

### Current Behavior

During the previous version, Chinese characters displayed well if using the CJK character set. However, when I updated the add-on to v2.0.12, the interface was filled with garbled characters. Then I checked the changed part of codes and found that CJK was deleted, so I wondered why this option was abandoned and how to get well with the new version.

### Expected Behavior

Fix the conflict between language and character sets.

### Steps To Reproduce

Use the 'language' option Chinese(simplified) and change the charator sets to Chinese(GBK), then the interface will show garbled characters.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
There are currently too many issues with the fontset. e.g. see these problems https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/110

I have removed it until I find a better approach.

**Comment by yangyiminger** [comment]
All right. Hope solved soon. Much love after all.

**Comment by jurialmunkey** [comment]
I have made an update to the CJK font resource which significantly improves matters by providing a properly spaced RobotoCondensed version instead of the old Roboto version. When used in combination with v2.0.14+ of the skin, it should give a significantly improved experience

It should update on my repo, but v0.0.2 of the font resource can also be found here:
https://github.com/jurialmunkey/resource.font.robotocjksc/releases/tag/v0.0.2

**Comment by yangyiminger** [comment]
Much appreciation! U deserve the donation.
