### ISSUE TITLE
:bug: When Kodi dim screensaver is enabled auto scroll still works but the show/movie title art doesn't change

### ISSUE THREAD

**Issue by booyakafoo** [jurialmunkey/skin.arctic.fuse.2#127]
### Skin section

Widgets

### Current Behavior

I have noticed that when the dim screensaver starts, the spotlight auto scroll between movies or shows will still work with the dimmed screen, but the title art and ratings don't change.  

Fanart and description continue to cycle to the next show/movie.

### Expected Behavior

Movie/Show title art and ratings should continue to cycle with the next show like background fanart and descriptions do.  

### Steps To Reproduce

Enable auto scroll time
Enable dim screensaver time of 1 minute
Wait at home screen and watch tv/movie spotlight scroll
After dim screensaver starts the fanart and description will continue scrolling but show title and ratings will be the last show before the screensaver started

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Tmdbhelper goes to sleep when the screensaver starts. This is intentional to save cycles while kodi is not in use

The "fix" to this issue would be for me to disable autoscroll while the screensaver is active.

A bit off topic, but I recommend using the Arctic Mirage screensaver - you can choose a media path and it will show a simple Netflix style slideshow of fanart plus plot and rating.

**Comment by booyakafoo** [comment]
Thanks for the info and work you're putting into this!   Really loving this skin.  I'll try out Arctic Mirage SS also.
