### ISSUE TITLE
Video OSD cast bio does not show

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse.2#131]
### Skin section

Video Info Dialog

### Current Behavior

When going to cast while video is playing, the actor bio does not populate. 

### Expected Behavior

When going to cast while video is playing, the actor bio populates. 

### Steps To Reproduce

1. Play video
2. Scroll down to a cast member
3. Click on cast member
4. Info should populate

### Screenshots and Additional Info

Going down to a cast member shows the bio blurb at the bottom. 
<img width="1106" alt="Screen Shot 2024-10-17 at 7 22 01 AM" src="https://github.com/user-attachments/assets/b176da52-8734-4575-9019-3501e3fd0d8e">

But when clicking on them, it is blank.
<img width="1106" alt="Screen Shot 2024-10-17 at 7 21 16 AM" src="https://github.com/user-attachments/assets/169f8119-7454-4dc8-9bf6-3dcddb9fcf5e">

However, it does show up when you just go into info and pull up cast.
<img width="1103" alt="Screen Shot 2024-10-17 at 7 24 28 AM" src="https://github.com/user-attachments/assets/2b2f522e-1fb5-4a9e-bbbf-224fde26ce00">

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Are you still having this issue? I've not been able to reproduce it.

**Comment by Liquidrag** [comment]
Yes, it's very odd actually, If I play a movie and pull up the cast, it is blank, but if I hit stop and play it again, it's all there. It's not a dealbreaker because I can always push right and the fly out bio pops up but figured you might have wanted to know.

**Comment by jurialmunkey** [comment]
>  If I play a movie and pull up the cast, it is blank, but if I hit stop and play it again, it's all there. 

This will be because bio is part of the extended details and it doesn't come with the cast lookup in the API. Once it's cached in TMDbHelper, it will get added automatically to the cast member next time you load it (which is what you see with stop/replay).

What is strange, however, is that those details are not showing up in the info dialog because you should still get a fallback to the service monitor pulling the extended details in. Might be that I've accidentally removed the fallback at some point.
EDIT: Yep, looks like that's exactly what I did. Should be an easy fix.

**Comment by Liquidrag** [comment]
Thank you!
