### ISSUE TITLE
Wrong title on main menu/combined widget

### ISSUE THREAD

**Issue by satelly1** [jurialmunkey/skin.arctic.fuse.2#144]
### Skin section

Widgets

### Current Behavior

When in the main menu or combined widget section, the video title appears to be reliant on TMDhelper (99950). However when in the main section, the video title is correct as it uses the local nfo data. I gather this is not a bug in the skin itself, but due to TMDhelper picking video title. However I see you have added features in #80 Reduce widget info reliance on 99950 fallbacks to improve plot ... and # 136 Show custom movie sets in movie info dialog. Can you extend the Use local cast/Use local information to the title for the main menu/combined widget. 

<img width="1231" alt="1" src="https://github.com/user-attachments/assets/62e697ea-b52e-4898-aa70-a5905021b9d2">

<img width="1235" alt="2" src="https://github.com/user-attachments/assets/6667d069-43c5-4051-877b-1609bb749616">

### Expected Behavior

Use local information as first preference for title for main menu/combined widget

### Steps To Reproduce

Go to main menu, scroll down to widget and again to combine widgets

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Yes this will always be a problem because Kodi does not have a way to specify a "current" widget ID to pull information from. Which means that when you don't have the widget focused, the skin must rely on TMDbHelper to fill in these details instead (or have them be blank which no one wants).

TMDbHelper must make a guess based upon the details of the item on what to lookup. Since this is specified as a TV show (but is actually a PVR recording of a live event) then TMDbHelper thinks it is a TV series and so tries to find that TV series on TMDb.

This ultimately boils down to a broader issue with how Kodi's database works and the lack of a more generic "videos" database to put items that don't fit neatly into TV Movies or MusicVideos (e.g. live tv recordings or home movies don't really fit any of these categories).

**Comment by jurialmunkey** [comment]
^^^ I think this is about as good as it will be possible to get. Will try to using base value from TMDbHelper before the online fallback.

Note for a tvshow this relies on TVShowTitle being set correctly in your library otherwise the online version will be used.

**Comment by satelly1** [comment]
Thanks very much for the new commit. It corrected it perfectly
