### ISSUE TITLE
Text scrolling does not always work

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse.2#161]
### Skin section

Other

### Current Behavior

Hi Jurial,
In the extension settings I sometimes miss a piece of text because the scrolling does not start. While on some lines it scrolls correctly, other times it does not, as if the text that is too long was not detected as such.

![image](https://github.com/user-attachments/assets/4692136e-e71b-4af2-87b7-0529b0115c00)

### Expected Behavior

Scroll the text whenever the text goes outside the box.

### Steps To Reproduce

Browse through the different lines of the extension settings.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Bindou01** [comment]
Text scrolling issues here too :
![image](https://github.com/user-attachments/assets/4dd24455-f5b3-429a-9a38-0218f6fe5d84)

**Comment by jurialmunkey** [comment]
The first issue I cannot fix. It is related to using a screen size which is not 16x9. The radiobutton controls don't have great control over textwidth resizing and it'd require too many workarounds to get working nicely -- I do my best to make sure the skin works okay on other aspect ratios but I can only official support 16x9, so there will be some issues like these on other aspects.

The second I should be able to fix - it's only because I added in the new add/delete buttons but didn't also reduce the label width by the corresponding amount.

**Comment by Bindou01** [comment]
![image](https://github.com/user-attachments/assets/30ebd3d2-d412-4618-b49d-0359d6d82daf)
Text no longer goes behind buttons. Perfect, thanks Jurial.

However, the scrolling behavior is still strange. The text of some Widget labels scrolls without them being selected, while others do not. Funny bug, no scrolling behaves the same way. However, it does not bother me, because they now all move, even if it is anarchic. Thanks Jurial!

Finally, the "reverse order" button has disappeared. Is this intentional ?
