### ISSUE TITLE
Extras button sometimes doesn't show on video info dialog when the movie has multiple versions

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse.2#196]
### Skin section

Video Info Dialog

### Current Behavior

When a movie has multiple versions and extras, it sometimes doesn't show the extras button on the "side-pull" dialog at the video info dialog. I tried to figure out when this happens, but could not find what causes it. Some movies it shows, some it doesn't.

(also, the extras dialog says "Versions" at the top.)

### Expected Behavior

Show extras button always if there are extras.

### Steps To Reproduce

1. Go to video info dialog of a movie that has multiple versions and extras
2. Pull op the side-dialog by pressing left
3. Notice that with some movies the extras button doesn't show

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Currently the skin checks the `HasVideoExtras` boolean onload of the info dialog to see if it should include the button. 

I wonder if maybe this value is not always evaluated before the dialog loads. I can switch it so that it is a visibility condition rather than an include condition and maybe that will help. 

Can you try the commit I just pushed and see if it makes a difference -- otherwise it might be a Kodi issue.

**Comment by Aemstel2** [comment]
No, that didn't seem to fix it.

**Comment by jurialmunkey** [comment]
This sounds it might also be a Kodi bug then unfortunately. The button should display if the HasVideoExtras is true, so that means it is not being set as true for some reason.
