### ISSUE TITLE
:bug: Unwanted options tray shortcuts

### ISSUE THREAD

**Issue by Kacper2Kaczmarek** [jurialmunkey/skin.arctic.fuse.2#226]
### Skin section

Other

### Current Behavior

When I start Kodi for the first time, in the options tray there are only the shortcuts that I set in the settings:
![image](https://github.com/user-attachments/assets/5630383f-b550-436c-a1ec-ece93ef6ca73)
![image](https://github.com/user-attachments/assets/76de0d08-bf78-4fc6-a4d3-62a61f0f6395)

However, once I play any video - no matter if it keeps playing in the background or if I stop it completely - two additional shortcuts appear in the tray:
![image](https://github.com/user-attachments/assets/807a2bb8-50b2-49b8-a9ea-5a290e8b5f44)
They stay there until the next Kodi restart.

### Expected Behavior

The expected behavior would be for the options to not change based on the fact if I played anything in Kodi since it was started.

### Steps To Reproduce

1. Run Kodi
2. Check how many shortcuts are in the options tray
4. Start any video
5. Stop the video
6. Check how many shortcuts are in the options tray again

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is normal.otherwise there is no way to get to the current play list.

**Comment by Kacper2Kaczmarek** [comment]
> This is normal.otherwise there is no way to get to the current play list.

While I understand it may be useful for some people while a video is playing in the background, does it make sense for the buttons to stay there till the next Kodi restart even though nothing is being played?

**Comment by jurialmunkey** [comment]
> buttons to stay there till the next Kodi restart even though nothing is being played

It was a holdover from AF1. It was deliberate but I do agree it feels a bit weird due to changes to playlist behaviour in Omega.

The check is based on whether the playlist has items. The thing is that in Omega *all* playback is via a playlist, even for a single item. So once you play something you have a playlist and it never gets cleared (which is different to how it worked in Nexus).

I've removed the controls here : https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/ed5f15ed823c4d3d42f084a50be09a20e690480c

I think it is enough to have controls when playing/paused but not stopped.

**Comment by Kacper2Kaczmarek** [comment]
That's great, thank you!
