### ISSUE TITLE
Combined view

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#26]
### Skin section

Widgets

### Current Behavior

So, I've created my TV Show widgets, that are all my takt lists I created.
But it seems to just be a continuous widget.
It's prob just me, but I cannot figure it out.

### Expected Behavior

Each category to have its own set of shows 

### Steps To Reproduce

Combined view 

### Screenshots and Additional Info

My settings

https://github.com/user-attachments/assets/9bad2bc2-50a9-43be-85e2-749c76623d1a

My lists

https://github.com/user-attachments/assets/59306de2-a525-4cf0-a306-b93df26a96a0

You can see in my set up video that in tv shows it opens up.

https://vimeo.com/manage/videos/1017154649

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You have to wait a moment on the button. It loads dynamically once you stop on the item.

**Comment by adamosborne83** [comment]
> You have to wait a moment on the button. It loads dynamically once you stop on the item.

Ok, I will send more info in a bit then, but I am testing this skin on 2 firecubes, both same widgets. 

The one with tv shows as Show Widget, takes longer to load that single one Amazon, 

Than the entire skin to load. With all 30 widgets.

**Comment by derrgoo** [comment]
Set limit at 10 and it will place an icon to load all. This makes it super fast. Plus if not cached it will be slow first time.

**Comment by adamosborne83** [comment]
> Set limit at 10 and it will place an icon to load all. This makes it super fast. Plus if not cached it will be slow first time. 

Only set to show 30, it's all cached too.

I will play some more as always.

**Comment by adamosborne83** [comment]
There has to be something...  I'm not newbie at skin editing ha....

I'm using library too, so that should be instant (ish)

![firetv_2024-10-09_18_38_49.jpg](https://github.com/user-attachments/assets/0af808a0-a598-48aa-8b5a-d2bef5d0c122)

https://imgur.com/a/ePYWK3z

**Comment by jurialmunkey** [comment]
Next update will allow for using combined mode with standard widgets.

Toggling combined will just use your normal widgets but in the combined style (IF no submenu list is specified) -- i.e. how it worked in AF1 (but with the added benefit of being a per category option). 

It will unfortunately mean that you have to set these up again as it no longer uses the separate submenu items (its now the widgets items) -- but it should simplify it for the future (you just have one set of widgets for the category and can toggle the layout). It also means you get all the normal widget benefits like individual styles/sorting etc. and it will static load.

The submenu list option is still there too, so if you want dynamic loading from a list you can still use that instead of individual widgets and it'll switch automatically to the dynamic mode (it's called "combined list" now to make it clearer).

**Comment by adamosborne83** [comment]
> Next update will allow for using combined mode with standard widgets.
> 
> Toggling combined will just use your normal widgets but in the combined style (IF no submenu list is specified) -- i.e. how it worked in AF1 (but with the added benefit of being a per category option). 
> 
> It will unfortunately mean that you have to set these up again as it no longer uses the separate submenu items (its now the widgets items) -- but it should simplify it for the future (you just have one set of widgets for the category and can toggle the layout). It also means you get all the normal widget benefits like individual styles/sorting etc. and it will static load.
> 
> The submenu list option is still there too, so if you want dynamic loading from a list you can still use that instead of individual widgets and it'll switch automatically to the dynamic mode (it's called "combined list" now to make it clearer).
> 

Look forward to playing tomorrow, thanks so much.

Did miss combined.
