### ISSUE TITLE
MPAA rating 

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse.2#265]
### Skin section

Widgets

### Current Behavior

Hi jurial

TMDB helper is not supporting Saudi Arabia as a region in automatically displaying MPAA ratings and I spoke to the guys in IMDB forums couple of years ago and apparently they  seized  further development in this area.

To my surprise the ratings do appear in the OSD screen, I am wondering if it is  a Metadata auto extraction by Kodi or there could a loophole that can be exploited  to inverse the process?

### Expected Behavior

Hopefully show MPAA ratings in hubs info line. 

### Steps To Reproduce

Play a video a pause. 

### Screenshots and Additional Info

![IMG_5142](https://github.com/user-attachments/assets/b1ae6316-70ca-4bd4-8d5c-53cc763b98da)
![IMG_5144](https://github.com/user-attachments/assets/d9e36317-bf85-4cf2-8ce9-4e35db64bf30)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's hard to say.

It's definitely not metadata extraction from the file.

It's either info stored in your library/plugin, or it is being pulled via TMDbHelper.

Considering that you have ratings displayed in both scenarios, I doubt it is coming from TMDbHelper. If you're using some sort of plugin (or something like Jellyfin / Plex etc.) it is possible that the plugin is only adding the MPAA on playback (especially if you're using TMDbHelper for the widget itself and then playing via another plugin using a player file).

**Comment by taiseer999** [comment]
Ratings only displays in the OSD infoline and it does to every video I stream... and not using Plex or Jellyfish, maybe its a plugin ...
Thanks for your reply.

**Comment by jurialmunkey** [comment]
> Ratings only displays in the OSD infoline and it does to every video I stream

No I mean in both your screenshots (widget and OSD) the ratings are displayed. And since these are the same ratings it shows that TMDbHelper is getting the same information in both cases.

That's why I dont think it is TMDbHelper -- otherwise we would expect to see the MPAA in both sets of info too.

**Comment by taiseer999** [comment]
its does only shows in the OSD screen here is another example 
![Screenshot 2024-11-01 at 11 05 28 AM](https://github.com/user-attachments/assets/240e5f30-db04-4dec-9279-9e1c22fb8a0a)
![Screenshot 2024-11-01 at 11 04 53 AM](https://github.com/user-attachments/assets/738b98e4-7497-4d65-b06c-e735a6442202)

**Comment by jurialmunkey** [comment]
Hahaha miscommunication. I was talking about ratings as in IMDb Trakt TMDb Metacritic etc. not as in MPAA! 😆 

What I meant is that because both Widget and OSD have Metacritic etc. ratings, that means that TMDbHelper must be successfully retrieving information from TMDb. Those rating scores only come via TMDbHelper and it can only look them up if it is also successful in doing a lookup of the movie information from TMDb.

Since the Metacritic etc. scores match in both scenarios, we know TMDbHelper is getting the same information from TMDb in both scenarios. So it can't be the source of the MPAA otherwise we'd see an MPAA rating in both scenarios too.

**Comment by taiseer999** [comment]
Thanks bro, going have to live with it :)

**Comment by L0bsang** [comment]
That's strange, Of course in English I have MPAA ratings in all cases.

I am noting that on the end of your infoline in Hubs there is a 'C' character, which isn't there on OSD infoline . Do you know what that is?

**Comment by taiseer999** [comment]
It's a mod to show if the movie is a sequel

**Comment by L0bsang** [comment]
> It's a mod to show if the movie is a sequel

Ah I see, like the one in Nimbus. 
Thanks for clarifying, I was wondering if due to limited space that was why your MPAA would not show. This collection indicator does not show on your OSD, seems to be one or the other can show.

**Comment by taiseer999** [comment]
Not really, info shows full in the infoline when tmdb region is USA, and problem is not new , I thought there could be a workaround to force mpaa ratings to appear in widgets infoline as they by God knows how display in OSD infoline.  
![Screenshot 2024-11-02 at 8 57 19 AM](https://github.com/user-attachments/assets/74734885-b51b-43b5-990c-90995c6c0524)
![Screenshot 2024-11-02 at 8 57 46 AM](https://github.com/user-attachments/assets/b0c3c643-282f-42cc-95fe-aa7ee92cd424)
