### ISSUE TITLE
:bug: 'Text' Titles Partially Obscured

### ISSUE THREAD

**Issue by jollyhiggler** [jurialmunkey/skin.arctic.fuse.2#273]
### Skin section

Widgets

### Current Behavior

Skin Settings / Interface / Style / Title: 'Text'

Title only partially visible. Title scrolls off top of screen even if single line. Info line jumps around according to title length. 

### Expected Behavior

Anchored Info Line. Visible, justified title.

Consistent row positioning as when 'logo' option is selected but logo unavailable (final screenshot)  

### Steps To Reproduce

Skin Settings / Interface / Style / Title: 'Text'

### Screenshots and Additional Info

![Screenshot (20)](https://github.com/user-attachments/assets/c788c56e-2e3e-438f-9860-15cdbaa8dddf)
![Screenshot (19)](https://github.com/user-attachments/assets/bcc94e64-ad71-4d98-aaab-3b0289bba061)
![Screenshot (22)](https://github.com/user-attachments/assets/afb08b37-a1f4-4269-96f6-1f638c3c72ec)
![Screenshot (23)](https://github.com/user-attachments/assets/b965a204-c37d-4d18-bf71-1fb54a40fb7d)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I can't reproduce.

This is a Kodi rendering issue with textbox control.

Are you using a non-standard resolution, or in windowed mode, or have a badly calibrated screen? 

In 1920x1080 in fullscreen, I am unable to reproduce this issue.

I can only reproduce the problem if I go into windowed mode and stretch the screen to a strange resolution.

**Comment by jurialmunkey** [comment]
![screenshot00789](https://github.com/user-attachments/assets/44d10b63-472e-4066-b989-a3776d52b5da)

![screenshot00790](https://github.com/user-attachments/assets/b5076f83-9ecf-445e-af37-8bf89037c358)

**Comment by jollyhiggler** [comment]
Both Full Screen and Windowed.
Windows laptop connected to a 16:9 monitor (2560x1440). The laptop screen is 16:10 (2880x1800). The effect is the same through either display.
Manually adjusting the Kodi resolution to 1920x1080 corrects the title visibility. 
The vertical positioning of the info line remains variable according to the length of the text title when skin setting is 'text' (fixed for text titles when skin setting set to 'logo'). Assuming this is by design / technical necessity?

**Comment by jurialmunkey** [comment]
> The vertical positioning of the info line remains variable according to the length of the text title when skin setting is 'text' (fixed for text titles when skin setting set to 'logo')

The difference in behaviour is intentional. With "logo" idea is to keep a static position since most items have logos and only a few have text (but at the expense of having a ridiculously large space for a single line of text). Whereas in "text", we use auto size height for the textbox to give a tighter alignment.

>Windows laptop connected to a 16:9 monitor (2560x1440). The laptop screen is 16:10 (2880x1800)

I think the issue is a rounding error in how Kodi is calculating textbox height.

Skin is defined for 1080p, so for Kodi to scale to 1440p it needs to multiply vertical by x1.33 (and for 1800p by x1.67) leading to a fractional pixel height. 

The rounding error makes Kodi's textbox auto height calculation off by 1 and it mucks up the rendering of vertically centered text

On my laptop, my screen is 2400x1600, so I when I test 16:9 by letterboxing to 2400x1350, the scaling is x1.25 factor. A much neater number, so I dont see the issue. But going fullscreen, I will.


Anyway, please try commit I pushed and see if that helps: https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/a3b8e949ae9225cba3ce1668bfba313f7e72e689

**Comment by jollyhiggler** [comment]
Many Thanks.

Yes - titles are now visible on both the upscaled 16:9 and the 16:10 displays.

On balance, personally I find the experience of scrolling through a row of text titles under the static "logo" condition to be a bit more comfortable on the eye than the auto-height "text" condition - particularly for rows of YouTube videos / obscure World Cinema. (It also avoided these rounding issues).  But I'm sure plenty of others will be of the opposite view 😉
