### ISSUE TITLE
Combined View, widget title scrolling.

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#303]
### Skin section

Widgets

### Current Behavior

Morning J,

Now I do not know if this is a bug, or intentional.

But, with title scrolling on widget name, if I am on one, it scrolls but then so will the one next to it.

Meaning that when I go onto it, it would have potentially stopped scrolling, due to the fact how kodi deals with scrolling titles.

### Expected Behavior

Only scrolls whilst on it.

### Steps To Reproduce

See video, whilst on Recently Added Movies, it scrolls, but so does Recebtly Watched. 

### Screenshots and Additional Info

https://github.com/user-attachments/assets/9935a90b-d6cf-439a-abb8-44b9d19cbd20

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
There's not much that can be done about it.

Because it is a fake list, you're not actually changing the control when you move. It is reusing the same button at each position. Only the label changes in the button when you move and then an animation fakes the appearance of moving up/down the list.

So once the button in a position has done its x3 scroll and stop, then it is done scrolling forever (until you reload the window).

And, yeah, really annoying that three scrolls and stops behaviour was never addressed. I would expect Kodi at the very least to retrigger the scroll if the label changes but unfortunately it does not.
