### ISSUE TITLE
:bug: Display occasionally never comes back after screensaver 

### ISSUE THREAD

**Issue by majikatsb** [jurialmunkey/skin.arctic.fuse.2#396]
### Skin section

Other

### Current Behavior

Ever since switching to AF2 (from AF), I've noticed a problem which occasionally appears after the system goes to screensaver.  My screensaver is just "Black" (which just blanks the screen) and this engages after 1 minute idle.  

Sometimes, when I press a button to come back from the screensaver, the display (on Sharp Aquos TV) won't wake up.  It just remains black and the system becomes unresponsive.  This has happened sometimes during audio playback and sometimes when doing nothing, i.e. just sitting on the a library page.  When playing audio, I have sometimes still been able to hear the audio, although the display never comes back.

Pressing any button on my remote or switching inputs all don't work.  In these cases, I've eventually had to reboot kodi.   

Without knowing much, this doesn't necessary seem to me like an issue which would be skin dependent, but rather, a more general Kodi (or OS, or hardware, etc.) issue.  However, I have never had this problem until I switched to Arctic Fuse 2 and now it happens a few times a week.  I used Arctic Fuse for many months before this without issue.  So I figured that I would check here just in case it's related.

### Expected Behavior

The display will come back after pressing a button to exit the screensaver.

### Steps To Reproduce

1. Setup Black as screensaver with a 1 minute wait time
2. Wait for 1 minute for screensaver to engage
3. Press any button on my remote
4. Display does not come back

### Screenshots and Additional Info

Here is a log file from the most recent time this happened:
https://paste.libreelec.tv/absolute-krill.log

Also, I don't know if it's related, but after the above log, I restarted kodi with `systemctl stop kodi`, `systemctl start kodi`.  Then when the skin loaded, with the first button I pressed, the system crashed.  That log is here: 
https://paste.libreelec.tv/becoming-poodle.log

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I've seen this happen before with the "Dim" screensaver where it gets stuck in its "on" state and the screen remains dim after Kodi wakes up. 

It's been a very long-standing issue see e.g. 
https://forum.kodi.tv/showthread.php?tid=131883
https://forum.kodi.tv/showthread.php?tid=347183

I have a feeling this might be effectively the same issue but because the screen is black it makes it appear unresponsive.

Not skin dependent as far as I know. Skins don't really have much to do with the screensaver at all so I can't even think how the skin might influence it.

There's some mention in those threads that it occurs when a skin update occurs, so that'd give an explanation as to why you're seeing it recently with AF2 (more frequent updates on my repo since I'm actively working on the skin).

**Comment by Bindou01** [comment]
I see this problem also manifests itself when there hasn't been an update for a while.
