### ISSUE TITLE
Fanart disappears when pressing context

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#409]
### Skin section

Widgets

### Current Behavior

Morning J, 
I'll be honest, I thought i had reported this before as its been happening a couple weeks now. So apologies, won't be able to tell you since which version.

But, when on library Movies if I click context, fanart disappears.

### Expected Behavior

Fanart to be consistent 

### Steps To Reproduce

Go onto a library Movies and click context 

### Screenshots and Additional Info

Famous video

https://github.com/user-attachments/assets/b2af8b05-9645-4a8b-b5bc-f1fbc32dc7ad

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I've not been able to reproduce this lately at all. I have had it happen in the past but haven't been able to since the last few versions of TMDbHelper.

What's strange in your video is that it is showing the fallback image for the spotlight. Have you set the skin to use that as fallback slideshow too?

**Comment by adamosborne83** [comment]
> I've not been able to reproduce this lately at all. I have had it happen in the past but haven't been able to since the last few versions of TMDbHelper.
> 
I'm guessing you pushed a fix? As it happens A LOT less now... the only way I could get it to happen, is if I source select an item, but then back out. A scenario that won't happen often, so I'll rarely see it.

https://github.com/user-attachments/assets/6f29115b-c220-4d30-9465-7a05b87d7e28



> What's strange in your video is that it is showing the fallback image for the spotlight. Have you set the skin to use that as fallback slideshow too?
> 
Yes, I change default. As you can see it makes it look more appealing than just having a black screen which would have been there before.

https://github.com/user-attachments/assets/abf94420-ac07-4002-9b54-71c41c430f33


>

**Comment by jurialmunkey** [comment]
> I'm guessing you pushed a fix? As it happens A LOT less now... the only way I could get it to happen, is if I source select an item, but then back out. A scenario that won't happen often, so I'll rarely see it.

In a roundabout way, yes a fix. Mostly to fix a timing issue of when the service checks that the additional details lookup still matches the focused item but will have a knock on effect here of better avoiding scenarios where it looks like the info is mismatched (and therefore it tries to clear it out).

And yes it will happen for any custom scripted dialogs. If the scripted window artwork is only a window property (and not attached to the items themselves) then the service will clear out the artwork properties because the focused item doesn't have any art.  

Since I don't control those windows, I'm not able to indicate that the service should pause while those are active -- but you should see it recover pretty quickly afterwards like in your video.

> Yes, I change default. As you can see it makes it look more appealing than just having a black screen which would have been there before.

Ah okay that's as expected then! I was just worried I'd made some weird mistake where the spotlight fallback was somehow coming into play.

**Comment by TeRubaus** [comment]
Hey, I just wanted to mention, that I'm also encountering this issue with **hidden** windows, where it's much more noticeable. I'm guessing that's not an issue to fix on your side, so feel free to ignore this, but I had an idea for a possible approach:

>Since I don't control those windows, I'm not able to indicate that the service should pause while those are active

Would it be possible to check the "visible" tag inside of a window's XML file? If the condition inside there is false, it would probably always make sense to keep the artwork properties.

**Comment by jurialmunkey** [comment]
Can't check properties/visible states of a window if I don't know what the ID of the window is in the first place.

There's already a property that windows can set to indicate that they are a contextual window.

The reason I can't do it for external addons or custom added windows is because I didn't write them.

**Comment by adamosborne83** [comment]
> Can't check properties/visible states of a window if I don't know what the ID of the window is in the first place.
> 
> There's already a property that windows can set to indicate that they are a contextual window.
> 
> The reason I can't do it for external addons or custom added windows is because I didn't write them. 

Morning J,

Just wanted to say, I installed your latest TMDbHelper commit, and this has now stopped for 95% of instances that it was happening in.
Now, additional fanart shows.
This is the same for library Movies, also, Trending which is addon related. 

See the famous videos.

This is library
https://github.com/user-attachments/assets/39fcfdec-0bf7-4ef7-87e9-9c2b77a2a498

This is addon
https://github.com/user-attachments/assets/facb3df6-e008-45d5-a6cb-bdcfdb9b53c3
