### ISSUE TITLE
Skinvariables-Shortcut-Sidemenu: Adding List

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.fuse.2#457]
### Skin section

Widgets

### Current Behavior

Hey there so I was transferring my addon_data of script.skinvariables to another device that's using Arctic Fuse 2 and I noticed that most of my icons are missing and I found out why. For some odd reason, whenever your adding a list to your shortcut menus, it will sometime do the full path, not the special path which is a problem if a user was to transfer his or her skin build to other devices.

![20241208_004905](https://github.com/user-attachments/assets/18a5b004-a230-45a6-b3d1-b8c5f8fa4061)
Sorry, was making this bug report on my phone.

### Expected Behavior

What I expected to happen is to see all my icons and everything when I transferred the skin variables files and that the icon paths should always be special paths. 

### Steps To Reproduce

1. Go to Edit Catagories and Widgets
2. Go to a menu, any menu is fine
3. Go to Edit Item
4. Use the add list button and add any menu items from an addon such as Tmdb Helper for example

Once you do all the steps above, you can find a file that could have been created in the app_data/script.skinvariables/nodes/skin.arctic.fuse.2

The file should be called "skinvariables-shortcut-sidemenu-customnode-guild-xxxxxxxxx" and it should contain menu items related to the addon you added the menu items from. 

### Screenshots and Additional Info

This took a long time to make a bug report on my phone. 😂

Anyway I hope all this information helped, if you could by anychance have icons use special paths for the skin variables, that would be amazing so that I can transfer my builds with all the icons. Its possible that it could just be a skin variables issue and not a skin issue but if it is, please transfer this issue to skin variables repo. 
Thank you 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is not a bug with the skin or skin variables.

Kodi will return the local path of the icon for the addon etc. when it is retrieved via json-rpc. Since Kodi does not return the special protocol version, then skin variables will never have that path.

If you want to use a special:// protocol path for custom icons, add the path as a source in file manager by manually inputting using the `special://` protocol path that points to the location you want to use for icons.

Then when adding an icon in the GUI, use the browse button on the right side and use back key to find the source folder you added. Then add the icon via that source folder and the special:// path will then be retained.

Alternatively, just do a find/replace in the json files to point to the special:// path equivalent.

All icons that come with the skin will use the special protocol by default. Anything else custom or a local position will need to be changed.

**Comment by Goldenfreddy0703** [comment]
Ahh i see, thank you very much for telling me about this. I did do a find/replace in the json files which helped a ton but i will do that for now on with any file changes i make to the skin. Thank you
