### ISSUE TITLE
:bug: Spotlight

### ISSUE THREAD

**Issue by BenVB1** [jurialmunkey/skin.arctic.fuse.2#61]
### Skin section

Widgets

### Current Behavior

Using Hub 1101 for Spotlight feature.
Display contains a large amount of empty space between the menu and info section. Submenu widgets are pushed almost offscreen.

### Expected Behavior

Same as AF1, would expect to see no empty space there.

### Steps To Reproduce

Turning Spotlight off results in expected display.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is not a bug. It is intended behaviour. Spotlight is design to give a more fullscreen view of content.

The only reason it was in a higher position in AF1 is because there needed to be room for categories / submenu, but this is no longer necessary. 

You can disable the spotlight if you only want detailed views.
