### ISSUE TITLE
:bug: Info section bugs

### ISSUE THREAD

**Issue by Navios92** [jurialmunkey/skin.arctic.fuse.2#80]
### Skin section

Widgets

### Current Behavior

Hi jurial,

I have noticed a couple of bugs with info section that I would like to report.

1- When the media title is long, it uses 2 lines which causes the plot to shift down. This didn't happen with AF1 as it used just one line for the titles. Now, I actually prefer the 2-lines titles and I would love for that to stay. Can we have that while having  the plot position fixed?
This happens on both the homescreen widgets and within addons.

![Screenshot_20241011-174450](https://github.com/user-attachments/assets/33d96440-f01f-4dad-aebd-ed5f76e7be20)

![Screenshot_20241011-174535](https://github.com/user-attachments/assets/85b1665e-41b5-40f4-bc14-e3134a0a4983)

2- The second bug happens only on homescreen widgets but not within addons. When fast scrolling, the titles take longer to load.

Homescreen:
https://github.com/user-attachments/assets/2ac4e0b4-c839-412c-beec-1607d50fef4f

Inside addons:
https://github.com/user-attachments/assets/8ab96ae2-1e6b-4741-9305-6c13ad351cdc

Sometimes the title of a media (widgets only) gets stuck and shows for the next item. This one however happens randomly and I can't reproduce right now.

Thanks!

### Expected Behavior

1- Position of the plot is fixed for both 1-line and 2-line titles.

2- Scrolling through widgets would behave the same as scrolling inside addons/library.

### Steps To Reproduce

Scroll through widgets with detailed info, while using text titles.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Navios92** [comment]
I should also mention that AF1 doesn't have the second bug.

**Comment by Navios92** [comment]
The bug where the titles get stuck has happened again.

Here is a video:

https://github.com/user-attachments/assets/6f124998-5085-4378-af51-1516813735e0

**Comment by jurialmunkey** [comment]
The first is intentional. Lots of technical reasons for it that I wont go into. There is also a practical reason which is to remove the kodi logo above the title that everyone complained about whilst still allowing for the smaller font to align correctly with the margin.

The second is TMDbHelper trying to catch up with you after sitting idle (or in the case of scrolling fast it has an interval it checks at to avoid looking up every item you scroll past and spamming the service). 

I have to use TMDbHelper for widgets to give a static widget container ID that I can reference. Otherwise the info would disappear as soon as you unfocused the item (e.g. if you moved to the side menu or opened context etc. then Kodi would show info for whatever is focused when of course you really want to see the info for the widget still). 

I'll see if the code can be refined a bit so as to only fallback when unfocused or the info is missing from the main item (e.g. you can see that's how the info line works).

**Comment by derrgoo** [comment]
One thing to add is it seems it takes allot of time to load information. Both on my shield pro and k6 box. This may be due to all the information it is pulling on actors.

**Comment by Navios92** [comment]
> The first is intentional. Lots of technical reasons for it that I wont go into. There is also a practical reason which is to remove the kodi logo above the title that everyone complained about whilst still allowing for the smaller font to align correctly with the margin.

I see. Well no problem then. It's worth it for the 2 lines titles imo. 


> I'll see if the code can be refined a bit so as to only fallback when unfocused or the info is missing from the main item (e.g. you can see that's how the info line works).

I updated to v2.0.8 and everything is fine now!
Thank you very much jurial!


EDIT: Sometimes the context menu shows the info for the wrong item. This happens also with AF1, but I'm not sure if it happened with AF2 before updating the code.
I can't pinpoint what causes it exactly. I think it happens if I scroll too fast or if the widgets are refreshing?
It's not a big deal though. Just thought I should mention it.

![Screenshot_20241013-115932](https://github.com/user-attachments/assets/7bf0014c-aabf-4112-b60f-176ade4d57d6)

**Comment by jurialmunkey** [comment]
> Sometimes the context menu shows the info for the wrong item. This happens also with AF1, but I'm not sure if it happened with AF2 before updating the code. I can't pinpoint what causes it exactly. I think it happens if I scroll too fast or if the widgets are refreshing?

Yeah I use a little cheat here to pass through the details from TMDbHelper -- but if you open the context menu quickly before it has updated to the current item, then you get whatever was previously loaded in the TMDbHelper service.

It's one of those things where it's always going to be a little buggy, but I like the effect of having the artwork enough that it outweighs the occasional rough edge with having the wrong artwork.

Eventually I'll make it optional so that it's one of those things where you can choose to either go with the experimental with the occassional buggy behaviour, or the simple but dependable version.

**Comment by Navios92** [comment]
> > Sometimes the context menu shows the info for the wrong item. This happens also with AF1, but I'm not sure if it happened with AF2 before updating the code. I can't pinpoint what causes it exactly. I think it happens if I scroll too fast or if the widgets are refreshing?
> 
> Yeah I use a little cheat here to pass through the details from TMDbHelper -- but if you open the context menu quickly before it has updated to the current item, then you get whatever was previously loaded in the TMDbHelper service.
> 
> It's one of those things where it's always going to be a little buggy, but I like the effect of having the artwork enough that it outweighs the occasional rough edge with having the wrong artwork.
> 
> Eventually I'll make it optional so that it's one of those things where you can choose to either go with the experimental with the occassional buggy behaviour, or the simple but dependable version.

I do like the artwork too. I think if I was actually using Kodi normally and not testing the skin to look for bugs, I wouldn't see this often.
But having the option for other people who might be annoyed by this is great ofc!

**Comment by derrgoo** [comment]
> One thing to add is it seems it takes allot of time to load information. Both on my shield pro and k6 box. This may be due to all the information it is pulling on actors. 

This has seemed to be very fast now since last few updates. 👍
